<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CidadesSeeder extends Seeder
{
    public function run()
    {
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Abatiá"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Adrianópolis"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Agudos do Sul"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Almirante Tamandaré"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Altamira do Paraná"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Alto Paraíso"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Alto Paraná"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Alto Piquiri"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Altônia"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Alvorada do Sul"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Amaporã"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Ampére"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Anahy"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Andirá"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Ângulo"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Antonina"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Antônio Olinto"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Apucarana"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Arapongas"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Arapoti"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Arapuã"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Araruna"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Araucária"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Ariranha do Ivaí"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Assaí"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Assis Chateaubriand"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Astorga"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Atalaia"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Balsa Nova"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Bandeirantes"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Barbosa Ferraz"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Barra do Jacaré"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Barracão"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Bela Vista da Caroba"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Bela Vista do Paraíso"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Bituruna"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Boa Esperança"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Boa Esperança do Iguaçu"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Boa Ventura de São Roque"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Boa Vista da Aparecida"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Bocaiúva do Sul"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Bom Jesus do Sul"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Bom Sucesso"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Bom Sucesso do Sul"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Borrazópolis"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Braganey"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Brasilândia do Sul"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Cafeara"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Cafelândia"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Cafezal do Sul"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Califórnia"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Cambará"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Cambé"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Cambira"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Campina da Lagoa"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Campina do Simão"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Campina Grande do Sul"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Campo Bonito"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Campo do Tenente"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Campo Largo"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Campo Magro"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Campo Mourão"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Cândido de Abreu"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Candói"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Cantagalo"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Capanema"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Capitão Leônidas Marques"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Carambeí"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Carlópolis"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Cascavel"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Castro"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Catanduvas"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Centenário do Sul"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Cerro Azul"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Céu Azul"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Chopinzinho"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Cianorte"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Cidade Gaúcha"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Clevelândia"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Colombo"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Colorado"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Congonhinhas"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Conselheiro Mairinck"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Contenda"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Corbélia"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Cornélio Procópio"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Coronel Domingos Soares"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Coronel Vivida"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Corumbataí do Sul"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Cruz Machado"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Cruzeiro do Iguaçu"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Cruzeiro do Oeste"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Cruzeiro do Sul"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Cruzmaltina"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Curitiba"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Curiúva"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Diamante do Norte"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Diamante do Sul"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Diamante D'Oeste"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Dois Vizinhos"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Douradina"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Doutor Camargo"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Doutor Ulysses"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Enéas Marques"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Engenheiro Beltrão"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Entre Rios do Oeste"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Esperança Nova"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Espigão Alto do Iguaçu"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Farol"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Faxinal"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Fazenda Rio Grande"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Fênix"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Fernandes Pinheiro"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Figueira"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Flor da Serra do Sul"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Floraí"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Floresta"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Florestópolis"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Flórida"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Formosa do Oeste"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Foz do Iguaçu"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Foz do Jordão"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Francisco Alves"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Francisco Beltrão"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "General Carneiro"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Godoy Moreira"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Goioerê"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Goioxim"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Grandes Rios"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Guaíra"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Guairaçá"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Guamiranga"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Guapirama"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Guaporema"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Guaraci"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Guaraniaçu"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Guarapuava"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Guaraqueçaba"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Guaratuba"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Honório Serpa"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Ibaiti"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Ibema"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Ibiporã"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Icaraíma"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Iguaraçu"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Iguatu"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Imbaú"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Imbituva"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Inácio Martins"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Inajá"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Indianópolis"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Ipiranga"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Iporã"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Iracema do Oeste"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Irati"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Iretama"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Itaguajé"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Itaipulândia"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Itambaracá"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Itambé"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Itapejara d'Oeste"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Itaperuçu"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Itaúna do Sul"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Ivaí"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Ivaiporã"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Ivaté"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Ivatuba"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Jaboti"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Jacarezinho"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Jaguapitã"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Jaguariaíva"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Jandaia do Sul"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Janiópolis"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Japira"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Japurá"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Jardim Alegre"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Jardim Olinda"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Jataizinho"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Jesuítas"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Joaquim Távora"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Jundiaí do Sul"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Juranda"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Jussara"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Kaloré"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Lapa"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Laranjal"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Laranjeiras do Sul"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Leópolis"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Lidianópolis"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Lindoeste"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Loanda"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Lobato"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Londrina"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Luiziana"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Lunardelli"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Lupionópolis"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Mallet"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Mamborê"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Mandaguaçu"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Mandaguari"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Mandirituba"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Manfrinópolis"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Mangueirinha"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Manoel Ribas"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Marechal Cândido Rondon"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Maria Helena"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Marialva"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Marilândia do Sul"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Marilena"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Mariluz"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Maringá"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Mariópolis"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Maripá"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Marmeleiro"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Marquinho"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Marumbi"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Matelândia"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Matinhos"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Mato Rico"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Mauá da Serra"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Medianeira"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Mercedes"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Mirador"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Miraselva"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Missal"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Moreira Sales"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Morretes"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Munhoz de Melo"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Nossa Senhora das Graças"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Nova Aliança do Ivaí"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Nova América da Colina"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Nova Aurora"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Nova Cantu"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Nova Esperança"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Nova Esperança do Sudoeste"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Nova Fátima"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Nova Laranjeiras"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Nova Londrina"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Nova Olímpia"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Nova Prata do Iguaçu"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Nova Santa Bárbara"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Nova Santa Rosa"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Nova Tebas"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Novo Itacolomi"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Ortigueira"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Ourizona"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Ouro Verde do Oeste"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Paiçandu"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Palmas"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Palmeira"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Palmital"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Palotina"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Paraíso do Norte"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Paranacity"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Paranaguá"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Paranapoema"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Paranavaí"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Pato Bragado"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Pato Branco"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Paula Freitas"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Paulo Frontin"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Peabiru"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Perobal"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Pérola"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Pérola d'Oeste"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Piên"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Pinhais"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Pinhal de São Bento"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Pinhalão"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Pinhão"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Piraí do Sul"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Piraquara"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Pitanga"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Pitangueiras"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Planaltina do Paraná"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Planalto"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Ponta Grossa"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Pontal do Paraná"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Porecatu"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Porto Amazonas"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Porto Barreiro"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Porto Rico"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Porto Vitória"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Prado Ferreira"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Pranchita"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Presidente Castelo Branco"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Primeiro de Maio"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Prudentópolis"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Quarto Centenário"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Quatiguá"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Quatro Barras"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Quatro Pontes"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Quedas do Iguaçu"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Querência do Norte"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Quinta do Sol"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Quitandinha"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Ramilândia"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Rancho Alegre"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Rancho Alegre D'Oeste"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Realeza"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Rebouças"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Renascença"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Reserva"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Reserva do Iguaçu"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Ribeirão Claro"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Ribeirão do Pinhal"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Rio Azul"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Rio Bom"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Rio Bonito do Iguaçu"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Rio Branco do Ivaí"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Rio Branco do Sul"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Rio Negro"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Rolândia"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Roncador"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Rondon"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Rosário do Ivaí"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Sabáudia"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Salgado Filho"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Salto do Itararé"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Salto do Lontra"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Santa Amélia"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Santa Cecília do Pavão"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Santa Cruz de Monte Castelo"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Santa Fé"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Santa Helena"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Santa Inês"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Santa Isabel do Ivaí"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Santa Izabel do Oeste"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Santa Lúcia"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Santa Maria do Oeste"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Santa Mariana"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Santa Mônica"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Santa Tereza do Oeste"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Santa Terezinha de Itaipu"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Santana do Itararé"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Santo Antônio da Platina"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Santo Antônio do Caiuá"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Santo Antônio do Paraíso"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Santo Antônio do Sudoeste"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Santo Inácio"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "São Carlos do Ivaí"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "São Jerônimo da Serra"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "São João"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "São João do Caiuá"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "São João do Ivaí"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "São João do Triunfo"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "São Jorge do Ivaí"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "São Jorge do Patrocínio"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "São Jorge d'Oeste"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "São José da Boa Vista"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "São José das Palmeiras"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "São José dos Pinhais"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "São Manoel do Paraná"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "São Mateus do Sul"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "São Miguel do Iguaçu"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "São Pedro do Iguaçu"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "São Pedro do Ivaí"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "São Pedro do Paraná"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "São Sebastião da Amoreira"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "São Tomé"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Sapopema"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Sarandi"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Saudade do Iguaçu"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Sengés"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Serranópolis do Iguaçu"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Sertaneja"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Sertanópolis"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Siqueira Campos"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Sulina"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Tamarana"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Tamboara"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Tapejara"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Tapira"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Teixeira Soares"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Telêmaco Borba"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Terra Boa"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Terra Rica"]);
        DB::table('cidades')->insert(['estado_id' => 1,  'nome' => "Terra Roxa"]);
        DB::table('cidades')->insert(['estado_id' => 1,  'nome' => "Tibagi"]);
        DB::table('cidades')->insert(['estado_id' => 1,  'nome' => "Tijucas do Sul"]);
        DB::table('cidades')->insert(['estado_id' => 1,  'nome' => "Toledo"]);
        DB::table('cidades')->insert(['estado_id' => 1,  'nome' => "Tomazina"]);
        DB::table('cidades')->insert(['estado_id' => 1,  'nome' => "Três Barras do Paraná"]);
        DB::table('cidades')->insert(['estado_id' => 1,  'nome' => "Tunas do Paraná"]);
        DB::table('cidades')->insert(['estado_id' => 1,  'nome' => "Tuneiras do Oeste"]);
        DB::table('cidades')->insert(['estado_id' => 1,  'nome' => "Tupãssi"]);
        DB::table('cidades')->insert(['estado_id' => 1,  'nome' => "Turvo"]);
        DB::table('cidades')->insert(['estado_id' => 1,  'nome' => "Ubiratã"]);
        DB::table('cidades')->insert(['estado_id' => 1,  'nome' => "Umuarama"]);
        DB::table('cidades')->insert(['estado_id' => 1,  'nome' => "União da Vitória"]);
        DB::table('cidades')->insert(['estado_id' => 1,  'nome' => "Uniflor"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Uraí"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Ventania"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Vera Cruz do Oeste"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Verê"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Virmond"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Vitorino"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Wenceslau Braz"]);
        DB::table('cidades')->insert(['estado_id' => 1, 'nome' => "Xambrê"]);
    }
}
